# Generated by Django 3.0.1 on 2020-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Property Name')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('price', models.FloatField(default=0.0)),
                ('area', models.FloatField(default=0.0, help_text='Enter area in sq. ft')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('proptery_type', models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], max_length=1)),
            ],
        ),
    ]
